// Code generated by ent, DO NOT EDIT.

package transactions

const (
	// Label holds the string label denoting the transactions type in the database.
	Label = "transactions"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// FieldTransactionID holds the string denoting the transactionid field in the database.
	FieldTransactionID = "transaction_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSender holds the string denoting the sender field in the database.
	FieldSender = "sender"
	// FieldRecipient holds the string denoting the recipient field in the database.
	FieldRecipient = "recipient"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPackage holds the string denoting the package field in the database.
	FieldPackage = "package"
	// FieldModule holds the string denoting the module field in the database.
	FieldModule = "module"
	// FieldFunction holds the string denoting the function field in the database.
	FieldFunction = "function"
	// Table holds the table name of the transactions in the database.
	Table = "transactions"
)

// Columns holds all SQL columns for transactions fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldTime,
	FieldTransactionID,
	FieldStatus,
	FieldSender,
	FieldRecipient,
	FieldAmount,
	FieldPackage,
	FieldModule,
	FieldFunction,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
