// Code generated by ent, DO NOT EDIT.

package pkg

const (
	// Label holds the string label denoting the pkg type in the database.
	Label = "pkg"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTransactionID holds the string denoting the transactionid field in the database.
	FieldTransactionID = "transaction_id"
	// FieldObjectID holds the string denoting the objectid field in the database.
	FieldObjectID = "object_id"
	// FieldBytecode holds the string denoting the bytecode field in the database.
	FieldBytecode = "bytecode"
	// Table holds the table name of the pkg in the database.
	Table = "pkgs"
)

// Columns holds all SQL columns for pkg fields.
var Columns = []string{
	FieldID,
	FieldTransactionID,
	FieldObjectID,
	FieldBytecode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
