// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccObject struct {
	ObjectID string                 `json:"ObjectId"`
	Type     string                 `json:"Type"`
	Metadata map[string]interface{} `json:"Metadata"`
}

type NFTCount struct {
	Type  string `json:"Type"`
	Count int    `json:"Count"`
}
