// Code generated by ent, DO NOT EDIT.

package accounts

const (
	// Label holds the string label denoting the accounts type in the database.
	Label = "accounts"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSequenceID holds the string denoting the sequenceid field in the database.
	FieldSequenceID = "sequence_id"
	// FieldAccountID holds the string denoting the accountid field in the database.
	FieldAccountID = "account_id"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldObjects holds the string denoting the objects field in the database.
	FieldObjects = "objects"
	// FieldTransactions holds the string denoting the transactions field in the database.
	FieldTransactions = "transactions"
	// Table holds the table name of the accounts in the database.
	Table = "accounts"
)

// Columns holds all SQL columns for accounts fields.
var Columns = []string{
	FieldID,
	FieldSequenceID,
	FieldAccountID,
	FieldBalance,
	FieldObjects,
	FieldTransactions,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
