// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"rei.io/rei/ent/accounts"
	"rei.io/rei/ent/predicate"
	"rei.io/rei/ent/schema"
)

// AccountsUpdate is the builder for updating Accounts entities.
type AccountsUpdate struct {
	config
	hooks    []Hook
	mutation *AccountsMutation
}

// Where appends a list predicates to the AccountsUpdate builder.
func (au *AccountsUpdate) Where(ps ...predicate.Accounts) *AccountsUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetAccountID sets the "AccountID" field.
func (au *AccountsUpdate) SetAccountID(s string) *AccountsUpdate {
	au.mutation.SetAccountID(s)
	return au
}

// SetBalance sets the "Balance" field.
func (au *AccountsUpdate) SetBalance(u uint64) *AccountsUpdate {
	au.mutation.ResetBalance()
	au.mutation.SetBalance(u)
	return au
}

// AddBalance adds u to the "Balance" field.
func (au *AccountsUpdate) AddBalance(u int64) *AccountsUpdate {
	au.mutation.AddBalance(u)
	return au
}

// SetObjects sets the "Objects" field.
func (au *AccountsUpdate) SetObjects(so []schema.AccObject) *AccountsUpdate {
	au.mutation.SetObjects(so)
	return au
}

// SetTransactions sets the "Transactions" field.
func (au *AccountsUpdate) SetTransactions(s []string) *AccountsUpdate {
	au.mutation.SetTransactions(s)
	return au
}

// SetTime sets the "Time" field.
func (au *AccountsUpdate) SetTime(t time.Time) *AccountsUpdate {
	au.mutation.SetTime(t)
	return au
}

// Mutation returns the AccountsMutation object of the builder.
func (au *AccountsUpdate) Mutation() *AccountsMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccountsUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(au.hooks) == 0 {
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountsUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountsUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountsUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AccountsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   accounts.Table,
			Columns: accounts.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: accounts.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.AccountID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accounts.FieldAccountID,
		})
	}
	if value, ok := au.mutation.Balance(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: accounts.FieldBalance,
		})
	}
	if value, ok := au.mutation.AddedBalance(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: accounts.FieldBalance,
		})
	}
	if value, ok := au.mutation.Objects(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: accounts.FieldObjects,
		})
	}
	if value, ok := au.mutation.Transactions(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: accounts.FieldTransactions,
		})
	}
	if value, ok := au.mutation.Time(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: accounts.FieldTime,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accounts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// AccountsUpdateOne is the builder for updating a single Accounts entity.
type AccountsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountsMutation
}

// SetAccountID sets the "AccountID" field.
func (auo *AccountsUpdateOne) SetAccountID(s string) *AccountsUpdateOne {
	auo.mutation.SetAccountID(s)
	return auo
}

// SetBalance sets the "Balance" field.
func (auo *AccountsUpdateOne) SetBalance(u uint64) *AccountsUpdateOne {
	auo.mutation.ResetBalance()
	auo.mutation.SetBalance(u)
	return auo
}

// AddBalance adds u to the "Balance" field.
func (auo *AccountsUpdateOne) AddBalance(u int64) *AccountsUpdateOne {
	auo.mutation.AddBalance(u)
	return auo
}

// SetObjects sets the "Objects" field.
func (auo *AccountsUpdateOne) SetObjects(so []schema.AccObject) *AccountsUpdateOne {
	auo.mutation.SetObjects(so)
	return auo
}

// SetTransactions sets the "Transactions" field.
func (auo *AccountsUpdateOne) SetTransactions(s []string) *AccountsUpdateOne {
	auo.mutation.SetTransactions(s)
	return auo
}

// SetTime sets the "Time" field.
func (auo *AccountsUpdateOne) SetTime(t time.Time) *AccountsUpdateOne {
	auo.mutation.SetTime(t)
	return auo
}

// Mutation returns the AccountsMutation object of the builder.
func (auo *AccountsUpdateOne) Mutation() *AccountsMutation {
	return auo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccountsUpdateOne) Select(field string, fields ...string) *AccountsUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Accounts entity.
func (auo *AccountsUpdateOne) Save(ctx context.Context) (*Accounts, error) {
	var (
		err  error
		node *Accounts
	)
	if len(auo.hooks) == 0 {
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, auo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Accounts)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AccountsMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountsUpdateOne) SaveX(ctx context.Context) *Accounts {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccountsUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountsUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AccountsUpdateOne) sqlSave(ctx context.Context) (_node *Accounts, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   accounts.Table,
			Columns: accounts.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: accounts.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Accounts.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accounts.FieldID)
		for _, f := range fields {
			if !accounts.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accounts.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.AccountID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accounts.FieldAccountID,
		})
	}
	if value, ok := auo.mutation.Balance(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: accounts.FieldBalance,
		})
	}
	if value, ok := auo.mutation.AddedBalance(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: accounts.FieldBalance,
		})
	}
	if value, ok := auo.mutation.Objects(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: accounts.FieldObjects,
		})
	}
	if value, ok := auo.mutation.Transactions(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: accounts.FieldTransactions,
		})
	}
	if value, ok := auo.mutation.Time(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: accounts.FieldTime,
		})
	}
	_node = &Accounts{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accounts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
