// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"rei.io/rei/ent/account"
	"rei.io/rei/ent/schema"
)

// Account is the model entity for the Account schema.
type Account struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SequenceID holds the value of the "SequenceID" field.
	SequenceID int64 `json:"SequenceID,omitempty"`
	// AccountID holds the value of the "AccountID" field.
	AccountID string `json:"AccountID,omitempty"`
	// Balance holds the value of the "Balance" field.
	Balance int64 `json:"Balance,omitempty"`
	// Objects holds the value of the "Objects" field.
	Objects []schema.AccObject `json:"Objects,omitempty"`
	// Transactions holds the value of the "Transactions" field.
	Transactions []string `json:"Transactions,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Account) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case account.FieldObjects, account.FieldTransactions:
			values[i] = new([]byte)
		case account.FieldID, account.FieldSequenceID, account.FieldBalance:
			values[i] = new(sql.NullInt64)
		case account.FieldAccountID:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Account", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Account fields.
func (a *Account) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case account.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case account.FieldSequenceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field SequenceID", values[i])
			} else if value.Valid {
				a.SequenceID = value.Int64
			}
		case account.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field AccountID", values[i])
			} else if value.Valid {
				a.AccountID = value.String
			}
		case account.FieldBalance:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field Balance", values[i])
			} else if value.Valid {
				a.Balance = value.Int64
			}
		case account.FieldObjects:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field Objects", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &a.Objects); err != nil {
					return fmt.Errorf("unmarshal field Objects: %w", err)
				}
			}
		case account.FieldTransactions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field Transactions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &a.Transactions); err != nil {
					return fmt.Errorf("unmarshal field Transactions: %w", err)
				}
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Account.
// Note that you need to call Account.Unwrap() before calling this method if this Account
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Account) Update() *AccountUpdateOne {
	return (&AccountClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the Account entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Account) Unwrap() *Account {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Account is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Account) String() string {
	var builder strings.Builder
	builder.WriteString("Account(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("SequenceID=")
	builder.WriteString(fmt.Sprintf("%v", a.SequenceID))
	builder.WriteString(", ")
	builder.WriteString("AccountID=")
	builder.WriteString(a.AccountID)
	builder.WriteString(", ")
	builder.WriteString("Balance=")
	builder.WriteString(fmt.Sprintf("%v", a.Balance))
	builder.WriteString(", ")
	builder.WriteString("Objects=")
	builder.WriteString(fmt.Sprintf("%v", a.Objects))
	builder.WriteString(", ")
	builder.WriteString("Transactions=")
	builder.WriteString(fmt.Sprintf("%v", a.Transactions))
	builder.WriteByte(')')
	return builder.String()
}

// Accounts is a parsable slice of Account.
type Accounts []*Account

func (a Accounts) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
