// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"github.com/goccy/go-json"
	"fmt"
	"sync"
	"sync/atomic"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/schema"
	"github.com/99designs/gqlgen/graphql"
	"github.com/hashicorp/go-multierror"
	"golang.org/x/sync/semaphore"
	"rei.io/rei/ent/accounts"
	"rei.io/rei/ent/arguments"
	"rei.io/rei/ent/events"
	"rei.io/rei/ent/nfts"
	"rei.io/rei/ent/objects"
	"rei.io/rei/ent/packages"
	"rei.io/rei/ent/sessions"
	"rei.io/rei/ent/transactions"
	"rei.io/rei/ent/users"
)

// Noder wraps the basic Node method.
type Noder interface {
	Node(context.Context) (*Node, error)
}

// Node in the graph.
type Node struct {
	ID     int      `json:"id,omitempty"`     // node id.
	Type   string   `json:"type,omitempty"`   // node type.
	Fields []*Field `json:"fields,omitempty"` // node fields.
	Edges  []*Edge  `json:"edges,omitempty"`  // node edges.
}

// Field of a node.
type Field struct {
	Type  string `json:"type,omitempty"`  // field type.
	Name  string `json:"name,omitempty"`  // field name (as in struct).
	Value string `json:"value,omitempty"` // stringified value.
}

// Edges between two nodes.
type Edge struct {
	Type string `json:"type,omitempty"` // edge type.
	Name string `json:"name,omitempty"` // edge name.
	IDs  []int  `json:"ids,omitempty"`  // node ids (where this edge point to).
}

func (a *Accounts) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     a.ID,
		Type:   "Accounts",
		Fields: make([]*Field, 5),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(a.SequenceID); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "uint64",
		Name:  "SequenceID",
		Value: string(buf),
	}
	if buf, err = json.Marshal(a.AccountID); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "AccountID",
		Value: string(buf),
	}
	if buf, err = json.Marshal(a.Balance); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "uint64",
		Name:  "Balance",
		Value: string(buf),
	}
	if buf, err = json.Marshal(a.Objects); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "[]schema.AccObject",
		Name:  "Objects",
		Value: string(buf),
	}
	if buf, err = json.Marshal(a.Transactions); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "[]string",
		Name:  "Transactions",
		Value: string(buf),
	}
	return node, nil
}

func (a *Arguments) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     a.ID,
		Type:   "Arguments",
		Fields: make([]*Field, 4),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(a.Name); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "Name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(a.Type); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "Type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(a.TransactionID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "TransactionID",
		Value: string(buf),
	}
	if buf, err = json.Marshal(a.Data); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "Data",
		Value: string(buf),
	}
	return node, nil
}

func (e *Events) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     e.ID,
		Type:   "Events",
		Fields: make([]*Field, 6),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(e.Type); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "Type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(e.Sender); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "Sender",
		Value: string(buf),
	}
	if buf, err = json.Marshal(e.Recipient); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "Recipient",
		Value: string(buf),
	}
	if buf, err = json.Marshal(e.TransactionID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "TransactionID",
		Value: string(buf),
	}
	if buf, err = json.Marshal(e.ObjectID); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "ObjectID",
		Value: string(buf),
	}
	if buf, err = json.Marshal(e.Version); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "uint32",
		Name:  "Version",
		Value: string(buf),
	}
	return node, nil
}

func (nt *NFTs) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     nt.ID,
		Type:   "NFTs",
		Fields: make([]*Field, 4),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(nt.ObjectID); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "ObjectID",
		Value: string(buf),
	}
	if buf, err = json.Marshal(nt.Type); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "Type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(nt.Metadata); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "map[string]interface {}",
		Name:  "Metadata",
		Value: string(buf),
	}
	if buf, err = json.Marshal(nt.SequenceID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "uint64",
		Name:  "SequenceID",
		Value: string(buf),
	}
	return node, nil
}

func (o *Objects) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     o.ID,
		Type:   "Objects",
		Fields: make([]*Field, 8),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(o.Status); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "Status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(o.DataType); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "DataType",
		Value: string(buf),
	}
	if buf, err = json.Marshal(o.Type); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "Type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(o.HasPublicTransfer); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "bool",
		Name:  "Has_public_transfer",
		Value: string(buf),
	}
	if buf, err = json.Marshal(o.Fields); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "map[string]interface {}",
		Name:  "Fields",
		Value: string(buf),
	}
	if buf, err = json.Marshal(o.Owner); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "Owner",
		Value: string(buf),
	}
	if buf, err = json.Marshal(o.ObjectID); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "ObjectID",
		Value: string(buf),
	}
	if buf, err = json.Marshal(o.SequenceID); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "uint64",
		Name:  "SequenceID",
		Value: string(buf),
	}
	return node, nil
}

func (pa *Packages) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     pa.ID,
		Type:   "Packages",
		Fields: make([]*Field, 3),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(pa.TransactionID); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "TransactionID",
		Value: string(buf),
	}
	if buf, err = json.Marshal(pa.ObjectID); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "ObjectID",
		Value: string(buf),
	}
	if buf, err = json.Marshal(pa.Bytecode); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "map[string]interface {}",
		Name:  "Bytecode",
		Value: string(buf),
	}
	return node, nil
}

func (s *Sessions) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     s.ID,
		Type:   "Sessions",
		Fields: make([]*Field, 3),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(s.Username); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "Username",
		Value: string(buf),
	}
	if buf, err = json.Marshal(s.LoginTime); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "LoginTime",
		Value: string(buf),
	}
	if buf, err = json.Marshal(s.LoginIP); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "LoginIP",
		Value: string(buf),
	}
	return node, nil
}

func (t *Transactions) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     t.ID,
		Type:   "Transactions",
		Fields: make([]*Field, 11),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(t.Type); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "Type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.Time); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "Time",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.TransactionID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "TransactionID",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.Status); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "bool",
		Name:  "Status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.Sender); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "Sender",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.Recipient); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "Recipient",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.Amount); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "float64",
		Name:  "Amount",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.Package); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "string",
		Name:  "Package",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.Module); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "string",
		Name:  "Module",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.Function); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "string",
		Name:  "Function",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.Gas); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "uint32",
		Name:  "Gas",
		Value: string(buf),
	}
	return node, nil
}

func (u *Users) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     u.ID,
		Type:   "Users",
		Fields: make([]*Field, 2),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(u.Username); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "Username",
		Value: string(buf),
	}
	if buf, err = json.Marshal(u.Hash); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "Hash",
		Value: string(buf),
	}
	return node, nil
}

func (c *Client) Node(ctx context.Context, id int) (*Node, error) {
	n, err := c.Noder(ctx, id)
	if err != nil {
		return nil, err
	}
	return n.Node(ctx)
}

var errNodeInvalidID = &NotFoundError{"node"}

// NodeOption allows configuring the Noder execution using functional options.
type NodeOption func(*nodeOptions)

// WithNodeType sets the node Type resolver function (i.e. the table to query).
// If was not provided, the table will be derived from the universal-id
// configuration as described in: https://entgo.io/docs/migrate/#universal-ids.
func WithNodeType(f func(context.Context, int) (string, error)) NodeOption {
	return func(o *nodeOptions) {
		o.nodeType = f
	}
}

// WithFixedNodeType sets the Type of the node to a fixed value.
func WithFixedNodeType(t string) NodeOption {
	return WithNodeType(func(context.Context, int) (string, error) {
		return t, nil
	})
}

type nodeOptions struct {
	nodeType func(context.Context, int) (string, error)
}

func (c *Client) newNodeOpts(opts []NodeOption) *nodeOptions {
	nopts := &nodeOptions{}
	for _, opt := range opts {
		opt(nopts)
	}
	if nopts.nodeType == nil {
		nopts.nodeType = func(ctx context.Context, id int) (string, error) {
			return c.tables.nodeType(ctx, c.driver, id)
		}
	}
	return nopts
}

// Noder returns a Node by its id. If the NodeType was not provided, it will
// be derived from the id value according to the universal-id configuration.
//
//	c.Noder(ctx, id)
//	c.Noder(ctx, id, ent.WithNodeType(typeResolver))
func (c *Client) Noder(ctx context.Context, id int, opts ...NodeOption) (_ Noder, err error) {
	defer func() {
		if IsNotFound(err) {
			err = multierror.Append(err, entgql.ErrNodeNotFound(id))
		}
	}()
	table, err := c.newNodeOpts(opts).nodeType(ctx, id)
	if err != nil {
		return nil, err
	}
	return c.noder(ctx, table, id)
}

func (c *Client) noder(ctx context.Context, table string, id int) (Noder, error) {
	switch table {
	case accounts.Table:
		query := c.Accounts.Query().
			Where(accounts.ID(id))
		query, err := query.CollectFields(ctx, "Accounts")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case arguments.Table:
		query := c.Arguments.Query().
			Where(arguments.ID(id))
		query, err := query.CollectFields(ctx, "Arguments")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case events.Table:
		query := c.Events.Query().
			Where(events.ID(id))
		query, err := query.CollectFields(ctx, "Events")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case nfts.Table:
		query := c.NFTs.Query().
			Where(nfts.ID(id))
		query, err := query.CollectFields(ctx, "NFTs")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case objects.Table:
		query := c.Objects.Query().
			Where(objects.ID(id))
		query, err := query.CollectFields(ctx, "Objects")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case packages.Table:
		query := c.Packages.Query().
			Where(packages.ID(id))
		query, err := query.CollectFields(ctx, "Packages")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case sessions.Table:
		query := c.Sessions.Query().
			Where(sessions.ID(id))
		query, err := query.CollectFields(ctx, "Sessions")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case transactions.Table:
		query := c.Transactions.Query().
			Where(transactions.ID(id))
		query, err := query.CollectFields(ctx, "Transactions")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case users.Table:
		query := c.Users.Query().
			Where(users.ID(id))
		query, err := query.CollectFields(ctx, "Users")
		if err != nil {
			return nil, err
		}
		n, err := query.Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	default:
		return nil, fmt.Errorf("cannot resolve noder from table %q: %w", table, errNodeInvalidID)
	}
}

func (c *Client) Noders(ctx context.Context, ids []int, opts ...NodeOption) ([]Noder, error) {
	switch len(ids) {
	case 1:
		noder, err := c.Noder(ctx, ids[0], opts...)
		if err != nil {
			return nil, err
		}
		return []Noder{noder}, nil
	case 0:
		return []Noder{}, nil
	}

	noders := make([]Noder, len(ids))
	errors := make([]error, len(ids))
	tables := make(map[string][]int)
	id2idx := make(map[int][]int, len(ids))
	nopts := c.newNodeOpts(opts)
	for i, id := range ids {
		table, err := nopts.nodeType(ctx, id)
		if err != nil {
			errors[i] = err
			continue
		}
		tables[table] = append(tables[table], id)
		id2idx[id] = append(id2idx[id], i)
	}

	for table, ids := range tables {
		nodes, err := c.noders(ctx, table, ids)
		if err != nil {
			for _, id := range ids {
				for _, idx := range id2idx[id] {
					errors[idx] = err
				}
			}
		} else {
			for i, id := range ids {
				for _, idx := range id2idx[id] {
					noders[idx] = nodes[i]
				}
			}
		}
	}

	for i, id := range ids {
		if errors[i] == nil {
			if noders[i] != nil {
				continue
			}
			errors[i] = entgql.ErrNodeNotFound(id)
		} else if IsNotFound(errors[i]) {
			errors[i] = multierror.Append(errors[i], entgql.ErrNodeNotFound(id))
		}
		ctx := graphql.WithPathContext(ctx,
			graphql.NewPathWithIndex(i),
		)
		graphql.AddError(ctx, errors[i])
	}
	return noders, nil
}

func (c *Client) noders(ctx context.Context, table string, ids []int) ([]Noder, error) {
	noders := make([]Noder, len(ids))
	idmap := make(map[int][]*Noder, len(ids))
	for i, id := range ids {
		idmap[id] = append(idmap[id], &noders[i])
	}
	switch table {
	case accounts.Table:
		query := c.Accounts.Query().
			Where(accounts.IDIn(ids...))
		query, err := query.CollectFields(ctx, "Accounts")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case arguments.Table:
		query := c.Arguments.Query().
			Where(arguments.IDIn(ids...))
		query, err := query.CollectFields(ctx, "Arguments")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case events.Table:
		query := c.Events.Query().
			Where(events.IDIn(ids...))
		query, err := query.CollectFields(ctx, "Events")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case nfts.Table:
		query := c.NFTs.Query().
			Where(nfts.IDIn(ids...))
		query, err := query.CollectFields(ctx, "NFTs")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case objects.Table:
		query := c.Objects.Query().
			Where(objects.IDIn(ids...))
		query, err := query.CollectFields(ctx, "Objects")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case packages.Table:
		query := c.Packages.Query().
			Where(packages.IDIn(ids...))
		query, err := query.CollectFields(ctx, "Packages")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case sessions.Table:
		query := c.Sessions.Query().
			Where(sessions.IDIn(ids...))
		query, err := query.CollectFields(ctx, "Sessions")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case transactions.Table:
		query := c.Transactions.Query().
			Where(transactions.IDIn(ids...))
		query, err := query.CollectFields(ctx, "Transactions")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case users.Table:
		query := c.Users.Query().
			Where(users.IDIn(ids...))
		query, err := query.CollectFields(ctx, "Users")
		if err != nil {
			return nil, err
		}
		nodes, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	default:
		return nil, fmt.Errorf("cannot resolve noders from table %q: %w", table, errNodeInvalidID)
	}
	return noders, nil
}

type tables struct {
	once  sync.Once
	sem   *semaphore.Weighted
	value atomic.Value
}

func (t *tables) nodeType(ctx context.Context, drv dialect.Driver, id int) (string, error) {
	tables, err := t.Load(ctx, drv)
	if err != nil {
		return "", err
	}
	idx := int(id / (1<<32 - 1))
	if idx < 0 || idx >= len(tables) {
		return "", fmt.Errorf("cannot resolve table from id %v: %w", id, errNodeInvalidID)
	}
	return tables[idx], nil
}

func (t *tables) Load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	t.once.Do(func() { t.sem = semaphore.NewWeighted(1) })
	if err := t.sem.Acquire(ctx, 1); err != nil {
		return nil, err
	}
	defer t.sem.Release(1)
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	tables, err := t.load(ctx, drv)
	if err == nil {
		t.value.Store(tables)
	}
	return tables, err
}

func (*tables) load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	rows := &sql.Rows{}
	query, args := sql.Dialect(drv.Dialect()).
		Select("type").
		From(sql.Table(schema.TypeTable)).
		OrderBy(sql.Asc("id")).
		Query()
	if err := drv.Query(ctx, query, args, rows); err != nil {
		return nil, err
	}
	defer rows.Close()
	var tables []string
	return tables, sql.ScanSlice(rows, &tables)
}
