// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"rei.io/rei/ent/nft"
)

// NFT is the model entity for the NFT schema.
type NFT struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ObjectID holds the value of the "ObjectID" field.
	ObjectID string `json:"ObjectID,omitempty"`
	// Type holds the value of the "Type" field.
	Type string `json:"Type,omitempty"`
	// Metadata holds the value of the "Metadata" field.
	Metadata map[string]interface{} `json:"Metadata,omitempty"`
	// SequenceID holds the value of the "SequenceID" field.
	SequenceID int64 `json:"SequenceID,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NFT) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case nft.FieldMetadata:
			values[i] = new([]byte)
		case nft.FieldID, nft.FieldSequenceID:
			values[i] = new(sql.NullInt64)
		case nft.FieldObjectID, nft.FieldType:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type NFT", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NFT fields.
func (n *NFT) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nft.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			n.ID = int(value.Int64)
		case nft.FieldObjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ObjectID", values[i])
			} else if value.Valid {
				n.ObjectID = value.String
			}
		case nft.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Type", values[i])
			} else if value.Valid {
				n.Type = value.String
			}
		case nft.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field Metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &n.Metadata); err != nil {
					return fmt.Errorf("unmarshal field Metadata: %w", err)
				}
			}
		case nft.FieldSequenceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field SequenceID", values[i])
			} else if value.Valid {
				n.SequenceID = value.Int64
			}
		}
	}
	return nil
}

// Update returns a builder for updating this NFT.
// Note that you need to call NFT.Unwrap() before calling this method if this NFT
// was returned from a transaction, and the transaction was committed or rolled back.
func (n *NFT) Update() *NFTUpdateOne {
	return (&NFTClient{config: n.config}).UpdateOne(n)
}

// Unwrap unwraps the NFT entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (n *NFT) Unwrap() *NFT {
	_tx, ok := n.config.driver.(*txDriver)
	if !ok {
		panic("ent: NFT is not a transactional entity")
	}
	n.config.driver = _tx.drv
	return n
}

// String implements the fmt.Stringer.
func (n *NFT) String() string {
	var builder strings.Builder
	builder.WriteString("NFT(")
	builder.WriteString(fmt.Sprintf("id=%v, ", n.ID))
	builder.WriteString("ObjectID=")
	builder.WriteString(n.ObjectID)
	builder.WriteString(", ")
	builder.WriteString("Type=")
	builder.WriteString(n.Type)
	builder.WriteString(", ")
	builder.WriteString("Metadata=")
	builder.WriteString(fmt.Sprintf("%v", n.Metadata))
	builder.WriteString(", ")
	builder.WriteString("SequenceID=")
	builder.WriteString(fmt.Sprintf("%v", n.SequenceID))
	builder.WriteByte(')')
	return builder.String()
}

// NFTs is a parsable slice of NFT.
type NFTs []*NFT

func (n NFTs) config(cfg config) {
	for _i := range n {
		n[_i].config = cfg
	}
}
