// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"rei.io/rei/ent/nft"
)

// NFTCreate is the builder for creating a NFT entity.
type NFTCreate struct {
	config
	mutation *NFTMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetObjectID sets the "ObjectID" field.
func (nc *NFTCreate) SetObjectID(s string) *NFTCreate {
	nc.mutation.SetObjectID(s)
	return nc
}

// SetType sets the "Type" field.
func (nc *NFTCreate) SetType(s string) *NFTCreate {
	nc.mutation.SetType(s)
	return nc
}

// SetMetadata sets the "Metadata" field.
func (nc *NFTCreate) SetMetadata(m map[string]interface{}) *NFTCreate {
	nc.mutation.SetMetadata(m)
	return nc
}

// SetSequenceID sets the "SequenceID" field.
func (nc *NFTCreate) SetSequenceID(u uint64) *NFTCreate {
	nc.mutation.SetSequenceID(u)
	return nc
}

// Mutation returns the NFTMutation object of the builder.
func (nc *NFTCreate) Mutation() *NFTMutation {
	return nc.mutation
}

// Save creates the NFT in the database.
func (nc *NFTCreate) Save(ctx context.Context) (*NFT, error) {
	var (
		err  error
		node *NFT
	)
	if len(nc.hooks) == 0 {
		if err = nc.check(); err != nil {
			return nil, err
		}
		node, err = nc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NFTMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nc.check(); err != nil {
				return nil, err
			}
			nc.mutation = mutation
			if node, err = nc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(nc.hooks) - 1; i >= 0; i-- {
			if nc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, nc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*NFT)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from NFTMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NFTCreate) SaveX(ctx context.Context) *NFT {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nc *NFTCreate) Exec(ctx context.Context) error {
	_, err := nc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nc *NFTCreate) ExecX(ctx context.Context) {
	if err := nc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NFTCreate) check() error {
	if _, ok := nc.mutation.ObjectID(); !ok {
		return &ValidationError{Name: "ObjectID", err: errors.New(`ent: missing required field "NFT.ObjectID"`)}
	}
	if _, ok := nc.mutation.GetType(); !ok {
		return &ValidationError{Name: "Type", err: errors.New(`ent: missing required field "NFT.Type"`)}
	}
	if _, ok := nc.mutation.Metadata(); !ok {
		return &ValidationError{Name: "Metadata", err: errors.New(`ent: missing required field "NFT.Metadata"`)}
	}
	if _, ok := nc.mutation.SequenceID(); !ok {
		return &ValidationError{Name: "SequenceID", err: errors.New(`ent: missing required field "NFT.SequenceID"`)}
	}
	return nil
}

func (nc *NFTCreate) sqlSave(ctx context.Context) (*NFT, error) {
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (nc *NFTCreate) createSpec() (*NFT, *sqlgraph.CreateSpec) {
	var (
		_node = &NFT{config: nc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: nft.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: nft.FieldID,
			},
		}
	)
	_spec.OnConflict = nc.conflict
	if value, ok := nc.mutation.ObjectID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: nft.FieldObjectID,
		})
		_node.ObjectID = value
	}
	if value, ok := nc.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: nft.FieldType,
		})
		_node.Type = value
	}
	if value, ok := nc.mutation.Metadata(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: nft.FieldMetadata,
		})
		_node.Metadata = value
	}
	if value, ok := nc.mutation.SequenceID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: nft.FieldSequenceID,
		})
		_node.SequenceID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NFT.Create().
//		SetObjectID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NFTUpsert) {
//			SetObjectID(v+v).
//		}).
//		Exec(ctx)
func (nc *NFTCreate) OnConflict(opts ...sql.ConflictOption) *NFTUpsertOne {
	nc.conflict = opts
	return &NFTUpsertOne{
		create: nc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NFT.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (nc *NFTCreate) OnConflictColumns(columns ...string) *NFTUpsertOne {
	nc.conflict = append(nc.conflict, sql.ConflictColumns(columns...))
	return &NFTUpsertOne{
		create: nc,
	}
}

type (
	// NFTUpsertOne is the builder for "upsert"-ing
	//  one NFT node.
	NFTUpsertOne struct {
		create *NFTCreate
	}

	// NFTUpsert is the "OnConflict" setter.
	NFTUpsert struct {
		*sql.UpdateSet
	}
)

// SetObjectID sets the "ObjectID" field.
func (u *NFTUpsert) SetObjectID(v string) *NFTUpsert {
	u.Set(nft.FieldObjectID, v)
	return u
}

// UpdateObjectID sets the "ObjectID" field to the value that was provided on create.
func (u *NFTUpsert) UpdateObjectID() *NFTUpsert {
	u.SetExcluded(nft.FieldObjectID)
	return u
}

// SetType sets the "Type" field.
func (u *NFTUpsert) SetType(v string) *NFTUpsert {
	u.Set(nft.FieldType, v)
	return u
}

// UpdateType sets the "Type" field to the value that was provided on create.
func (u *NFTUpsert) UpdateType() *NFTUpsert {
	u.SetExcluded(nft.FieldType)
	return u
}

// SetMetadata sets the "Metadata" field.
func (u *NFTUpsert) SetMetadata(v map[string]interface{}) *NFTUpsert {
	u.Set(nft.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "Metadata" field to the value that was provided on create.
func (u *NFTUpsert) UpdateMetadata() *NFTUpsert {
	u.SetExcluded(nft.FieldMetadata)
	return u
}

// SetSequenceID sets the "SequenceID" field.
func (u *NFTUpsert) SetSequenceID(v uint64) *NFTUpsert {
	u.Set(nft.FieldSequenceID, v)
	return u
}

// UpdateSequenceID sets the "SequenceID" field to the value that was provided on create.
func (u *NFTUpsert) UpdateSequenceID() *NFTUpsert {
	u.SetExcluded(nft.FieldSequenceID)
	return u
}

// AddSequenceID adds v to the "SequenceID" field.
func (u *NFTUpsert) AddSequenceID(v uint64) *NFTUpsert {
	u.Add(nft.FieldSequenceID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NFT.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NFTUpsertOne) UpdateNewValues() *NFTUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NFT.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NFTUpsertOne) Ignore() *NFTUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NFTUpsertOne) DoNothing() *NFTUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NFTCreate.OnConflict
// documentation for more info.
func (u *NFTUpsertOne) Update(set func(*NFTUpsert)) *NFTUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NFTUpsert{UpdateSet: update})
	}))
	return u
}

// SetObjectID sets the "ObjectID" field.
func (u *NFTUpsertOne) SetObjectID(v string) *NFTUpsertOne {
	return u.Update(func(s *NFTUpsert) {
		s.SetObjectID(v)
	})
}

// UpdateObjectID sets the "ObjectID" field to the value that was provided on create.
func (u *NFTUpsertOne) UpdateObjectID() *NFTUpsertOne {
	return u.Update(func(s *NFTUpsert) {
		s.UpdateObjectID()
	})
}

// SetType sets the "Type" field.
func (u *NFTUpsertOne) SetType(v string) *NFTUpsertOne {
	return u.Update(func(s *NFTUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "Type" field to the value that was provided on create.
func (u *NFTUpsertOne) UpdateType() *NFTUpsertOne {
	return u.Update(func(s *NFTUpsert) {
		s.UpdateType()
	})
}

// SetMetadata sets the "Metadata" field.
func (u *NFTUpsertOne) SetMetadata(v map[string]interface{}) *NFTUpsertOne {
	return u.Update(func(s *NFTUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "Metadata" field to the value that was provided on create.
func (u *NFTUpsertOne) UpdateMetadata() *NFTUpsertOne {
	return u.Update(func(s *NFTUpsert) {
		s.UpdateMetadata()
	})
}

// SetSequenceID sets the "SequenceID" field.
func (u *NFTUpsertOne) SetSequenceID(v uint64) *NFTUpsertOne {
	return u.Update(func(s *NFTUpsert) {
		s.SetSequenceID(v)
	})
}

// AddSequenceID adds v to the "SequenceID" field.
func (u *NFTUpsertOne) AddSequenceID(v uint64) *NFTUpsertOne {
	return u.Update(func(s *NFTUpsert) {
		s.AddSequenceID(v)
	})
}

// UpdateSequenceID sets the "SequenceID" field to the value that was provided on create.
func (u *NFTUpsertOne) UpdateSequenceID() *NFTUpsertOne {
	return u.Update(func(s *NFTUpsert) {
		s.UpdateSequenceID()
	})
}

// Exec executes the query.
func (u *NFTUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NFTCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NFTUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NFTUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NFTUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NFTCreateBulk is the builder for creating many NFT entities in bulk.
type NFTCreateBulk struct {
	config
	builders []*NFTCreate
	conflict []sql.ConflictOption
}

// Save creates the NFT entities in the database.
func (ncb *NFTCreateBulk) Save(ctx context.Context) ([]*NFT, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*NFT, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NFTMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ncb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NFTCreateBulk) SaveX(ctx context.Context) []*NFT {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncb *NFTCreateBulk) Exec(ctx context.Context) error {
	_, err := ncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncb *NFTCreateBulk) ExecX(ctx context.Context) {
	if err := ncb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NFT.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NFTUpsert) {
//			SetObjectID(v+v).
//		}).
//		Exec(ctx)
func (ncb *NFTCreateBulk) OnConflict(opts ...sql.ConflictOption) *NFTUpsertBulk {
	ncb.conflict = opts
	return &NFTUpsertBulk{
		create: ncb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NFT.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ncb *NFTCreateBulk) OnConflictColumns(columns ...string) *NFTUpsertBulk {
	ncb.conflict = append(ncb.conflict, sql.ConflictColumns(columns...))
	return &NFTUpsertBulk{
		create: ncb,
	}
}

// NFTUpsertBulk is the builder for "upsert"-ing
// a bulk of NFT nodes.
type NFTUpsertBulk struct {
	create *NFTCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NFT.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NFTUpsertBulk) UpdateNewValues() *NFTUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NFT.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NFTUpsertBulk) Ignore() *NFTUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NFTUpsertBulk) DoNothing() *NFTUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NFTCreateBulk.OnConflict
// documentation for more info.
func (u *NFTUpsertBulk) Update(set func(*NFTUpsert)) *NFTUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NFTUpsert{UpdateSet: update})
	}))
	return u
}

// SetObjectID sets the "ObjectID" field.
func (u *NFTUpsertBulk) SetObjectID(v string) *NFTUpsertBulk {
	return u.Update(func(s *NFTUpsert) {
		s.SetObjectID(v)
	})
}

// UpdateObjectID sets the "ObjectID" field to the value that was provided on create.
func (u *NFTUpsertBulk) UpdateObjectID() *NFTUpsertBulk {
	return u.Update(func(s *NFTUpsert) {
		s.UpdateObjectID()
	})
}

// SetType sets the "Type" field.
func (u *NFTUpsertBulk) SetType(v string) *NFTUpsertBulk {
	return u.Update(func(s *NFTUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "Type" field to the value that was provided on create.
func (u *NFTUpsertBulk) UpdateType() *NFTUpsertBulk {
	return u.Update(func(s *NFTUpsert) {
		s.UpdateType()
	})
}

// SetMetadata sets the "Metadata" field.
func (u *NFTUpsertBulk) SetMetadata(v map[string]interface{}) *NFTUpsertBulk {
	return u.Update(func(s *NFTUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "Metadata" field to the value that was provided on create.
func (u *NFTUpsertBulk) UpdateMetadata() *NFTUpsertBulk {
	return u.Update(func(s *NFTUpsert) {
		s.UpdateMetadata()
	})
}

// SetSequenceID sets the "SequenceID" field.
func (u *NFTUpsertBulk) SetSequenceID(v uint64) *NFTUpsertBulk {
	return u.Update(func(s *NFTUpsert) {
		s.SetSequenceID(v)
	})
}

// AddSequenceID adds v to the "SequenceID" field.
func (u *NFTUpsertBulk) AddSequenceID(v uint64) *NFTUpsertBulk {
	return u.Update(func(s *NFTUpsert) {
		s.AddSequenceID(v)
	})
}

// UpdateSequenceID sets the "SequenceID" field to the value that was provided on create.
func (u *NFTUpsertBulk) UpdateSequenceID() *NFTUpsertBulk {
	return u.Update(func(s *NFTUpsert) {
		s.UpdateSequenceID()
	})
}

// Exec executes the query.
func (u *NFTUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NFTCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NFTCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NFTUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
