// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"rei.io/rei/ent/sessions"
)

// SessionsCreate is the builder for creating a Sessions entity.
type SessionsCreate struct {
	config
	mutation *SessionsMutation
	hooks    []Hook
}

// SetUsername sets the "Username" field.
func (sc *SessionsCreate) SetUsername(s string) *SessionsCreate {
	sc.mutation.SetUsername(s)
	return sc
}

// SetLoginTime sets the "LoginTime" field.
func (sc *SessionsCreate) SetLoginTime(t time.Time) *SessionsCreate {
	sc.mutation.SetLoginTime(t)
	return sc
}

// SetLoginIP sets the "LoginIP" field.
func (sc *SessionsCreate) SetLoginIP(s string) *SessionsCreate {
	sc.mutation.SetLoginIP(s)
	return sc
}

// Mutation returns the SessionsMutation object of the builder.
func (sc *SessionsCreate) Mutation() *SessionsMutation {
	return sc.mutation
}

// Save creates the Sessions in the database.
func (sc *SessionsCreate) Save(ctx context.Context) (*Sessions, error) {
	var (
		err  error
		node *Sessions
	)
	if len(sc.hooks) == 0 {
		if err = sc.check(); err != nil {
			return nil, err
		}
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SessionsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sc.check(); err != nil {
				return nil, err
			}
			sc.mutation = mutation
			if node, err = sc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			if sc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, sc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Sessions)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SessionsMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SessionsCreate) SaveX(ctx context.Context) *Sessions {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SessionsCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SessionsCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SessionsCreate) check() error {
	if _, ok := sc.mutation.Username(); !ok {
		return &ValidationError{Name: "Username", err: errors.New(`ent: missing required field "Sessions.Username"`)}
	}
	if _, ok := sc.mutation.LoginTime(); !ok {
		return &ValidationError{Name: "LoginTime", err: errors.New(`ent: missing required field "Sessions.LoginTime"`)}
	}
	if _, ok := sc.mutation.LoginIP(); !ok {
		return &ValidationError{Name: "LoginIP", err: errors.New(`ent: missing required field "Sessions.LoginIP"`)}
	}
	return nil
}

func (sc *SessionsCreate) sqlSave(ctx context.Context) (*Sessions, error) {
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (sc *SessionsCreate) createSpec() (*Sessions, *sqlgraph.CreateSpec) {
	var (
		_node = &Sessions{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: sessions.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sessions.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Username(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sessions.FieldUsername,
		})
		_node.Username = value
	}
	if value, ok := sc.mutation.LoginTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: sessions.FieldLoginTime,
		})
		_node.LoginTime = value
	}
	if value, ok := sc.mutation.LoginIP(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sessions.FieldLoginIP,
		})
		_node.LoginIP = value
	}
	return _node, _spec
}

// SessionsCreateBulk is the builder for creating many Sessions entities in bulk.
type SessionsCreateBulk struct {
	config
	builders []*SessionsCreate
}

// Save creates the Sessions entities in the database.
func (scb *SessionsCreateBulk) Save(ctx context.Context) ([]*Sessions, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Sessions, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SessionsCreateBulk) SaveX(ctx context.Context) []*Sessions {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SessionsCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SessionsCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
