// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Argument is the predicate function for argument builders.
type Argument func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// NFT is the predicate function for nft builders.
type NFT func(*sql.Selector)

// Object is the predicate function for object builders.
type Object func(*sql.Selector)

// Pkg is the predicate function for pkg builders.
type Pkg func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
